### ISSUE TITLE
LICENSE file and copyright notice

### ISSUE THREAD

**Issue by neatonk** [spinamp/web3-music-pipeline#34]
I see from the `package.json` file that this project is using the [ISC license](https://spdx.org/licenses/ISC.html), which requires the copyright notice and license text be included with any copies. If you would like to add a LICENSE file with a copyright notice in it, I'd gladly include that when making use of this code elsewhere.

Thanks for this great project! I've enjoyed digging into the code and listening to the results on spinamp.

**Comment by musnit** [comment]
@neatonk Ah, thanks for pointing this out. This isn't actually ISC licensed - that's just what was autogenerated. I'll add the LICENSE file in the coming days!

**Comment by musnit** [comment]
@neatonk https://github.com/spinamp/web3-music-pipeline/blob/main/LICENSE we're going with this for now.

would love to hear more about your use case/goals and how you're intending to use or help grow the project!

**Comment by neatonk** [comment]
Good choice and thanks for clarifying. Would be happy to chat sometime.
